name: moeboo
description: "Album de fotos de animes"

version: 1.1.4+14

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  async_wallpaper: ^2.0.3
  cupertino_icons: ^1.0.8
  file: ^7.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_vlc_player: ^7.4.1
  flutter_windowmanager: ^0.2.0
  html: ^0.15.4
  http: ^1.2.1
  image: ^4.2.0
  image_compression_flutter: ^1.0.4
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  network_to_file_image: ^6.0.1
  palette_generator: ^0.3.3+3
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  video_player: ^2.8.6
  win32: ^5.5.1
  xml2json: ^6.2.3
  showcaseview: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  #  flutter_launcher_name: ^0.0.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icons/ic_launcher.jpg"
    icon_size: 256

flutter_launcher_name:
  name: "MoeBoo"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/ca/